config/routes.rb
Hotels::Application.routes.draw do
  devise_for :users
  resources :hotels do
    resources :reviews
  end

   root 'tops#index'

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
 
  has_many :reviews  

  mount_uploader :photo, ImageUploader
  validates :name, presence: true, length: {maximum: 50}
  validates :rating, presence: true, length: {maximum: 5}

  def self.latest
    Hotel.order(:updated_at).last
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :hotel
  validates_presence_of :title, :rating, :comment 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hotel }
      else
        format.html { render action: 'new' }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :rating, :breakfast, :description, :price, :photo, :address)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

 before_action :review_params, only: [:create]
  def new
    @hotel = Hotel.find(params[:hotel_id])
    @review = Review.new
  end

  def index
    @reviews = Review.all
    @hotels = Hotel.all
  end

  def create
    hotel = Hotel.find(params[:hotel_id])
    @review = hotel.reviews.create(review_params)
    @review.title = current_user.email
    respond_to do |format|
    if @review.save
      format.html { redirect_to root_path }
    end
    end
  end

  private 

  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :comment, :rating)
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index 
    @hotels = Hotel.order("Created_at DESC").limit(5)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating, min: 0, max: 5 %>
  </div>
  <div class="field">
    <%= f.label :breakfast %><br>
    <%= f.check_box :breakfast %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Breakfast</th>
      <th>Description</th>
      <th>Price</th>
      <th>Photo</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.rating %></td>
        <td><%= hotel.breakfast %></td>
        <td><%= hotel.description %></td>
        <td><%= hotel.price %></td>
        <td><%= hotel.photo %></td>
        <td><%= hotel.address %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @hotel.rating %>
</p>

<p>
  <strong>Breakfast:</strong>
  <%= @hotel.breakfast %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hotel.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @hotel.price %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @hotel.photo %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hotels" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Hotel Advisor</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Top", root_path  %></li>
              <% if user_signed_in? %>
                 <li>
                   <%= link_to "Logout" ,destroy_user_session_path, method: :delete %></li>
                 </li>
		 <li class="loginn">
                   Logged in as <%= current_user.email.split("@").first %>
                 </li>
               <% else %>
                 <li>
                 <%= link_to "Login", new_user_session_path %>
                 </li>
               <% end %>
              <li><%= link_to "Add Hotel", hotels_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/reviews/_form.html.erb
  <%= form_for([@hotel,@review], html: { class: 'horizontal-form'}) do |f| %>

    <div class="field">
      <%= f.label :rating %><br>
      <%= f.number_field :rating, min: 0, max: 5 %>
    </div>
    <div class="field">
      <%= f.label :comment %><br>
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/reviews/new.html.erb
<div class="col-lg-6">
  <%= render 'form' %>
</div>

app/views/tops/_hotels.html.erb
<% cache ['hotel', Hotel.latest] do %>
  <%= @hotels.each do |hotel| %>
  <% cache ['main_p', hotel] do%>
      <div class='main_p'>
        <%= image_tag(hotel.photo) %>
        <div class="one">
          <h3><%= hotel.name %></h3>
          <p class="desc"><%= sanitize(hotel.description) %></p>
        </div>  
        <div class="price_line">
          <span class="price"><%= number_to_currency(hotel.price) %>  
        </div> 
        <div>
	  <p><%= hotel.breakfast %></p>
        </div>
        <div>
	  <p><%= hotel.address %></p>
        </div>
        <div>
	  <p><%= hotel.reviews.average("rating") %>/5</p>
        </div>
        <div class="review">
          <p><%= link_to "Add comment", new_hotel_review_path( hotel_id: hotel.id),  :class => 'btn btn-default' %></p> 
        </div>
	 <%= hotel.reviews.each do |review| %>
           <div>
             <p><%= review.title %></p>
           </div>
           <div>
             <p><%= review.rating %></p>
           </div>
           <div>
             <p><%= review.comment %></p>
           </div>
        <% end %>
      </div>
  <% end %>  
  <% end %>
<% end %>

app/views/tops/index.html.erb
<h2>Top products</h2>
  <div class="hotels">
    <%= render 'hotels' %>
  </div>